# Generated by Django 3.1.6 on 2021-02-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.BigIntegerField(max_length=200)),
                ('qty', models.IntegerField(max_length=200)),
                ('expired_date', models.DateTimeField()),
            ],
        ),
    ]
