# Generated by Django 3.1.6 on 2021-02-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstore',
            name='price',
            field=models.IntegerField(max_length=200),
        ),
    ]
