# Generated by Django 3.1.6 on 2021-02-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20210220_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstore',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medicalstore',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
