# Generated by Django 3.1.6 on 2021-02-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_auto_20210220_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstore',
            name='expired_date',
            field=models.TimeField(),
        ),
    ]
