# Generated by Django 3.1.6 on 2021-02-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20210220_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalstore',
            old_name='price',
            new_name='box_qty',
        ),
        migrations.AlterField(
            model_name='medicalstore',
            name='expired_date',
            field=models.DateField(),
        ),
    ]
